// Generated by pdf-versioning.
#let document-branch = "main"
#let document-built-at = "2026-06-29T11:47:28Z"
#let document-version-id = "main@2026-06-29T11:47:28Z"
#let document-base-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations"
#let document-version-check-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations/?pdfBranch=main&pdfBuiltAt=2026-06-29T11%3A47%3A28Z"
#let document-pdf-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations/main.pdf"
#let document-source-url = "https://github.com/kimpossible-TY/Partial-Differential-Equations/tree/dd8ed48611762de94eeb326b04315df15e4dbefb"
