// Generated by pdf-versioning.
#let document-branch = "main"
#let document-built-at = "2026-10-01T06:52:16Z"
#let document-version-id = "main@2026-10-01T06:52:16Z"
#let document-base-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations"
#let document-version-check-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations/?pdfBranch=main&pdfBuiltAt=2026-10-01T06%3A52%3A16Z"
#let document-pdf-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations/main.pdf"
#let document-source-url = "https://github.com/kimpossible-TY/Partial-Differential-Equations/tree/31e50272d59789f184799180bcc91bba756fb436"
