// Generated by pdf-versioning.
#let document-branch = "main"
#let document-built-at = "2026-07-18T03:53:06Z"
#let document-version-id = "main@2026-07-18T03:53:06Z"
#let document-base-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations"
#let document-version-check-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations/?pdfBranch=main&pdfBuiltAt=2026-07-18T03%3A53%3A06Z"
#let document-pdf-url = "https://kimpossible-ty.github.io/Partial-Differential-Equations/main.pdf"
#let document-source-url = "https://github.com/kimpossible-TY/Partial-Differential-Equations/tree/af7cab2103d5f664eb18faaf48e2510a7486b5f4"
